Parking/Models/ErrorViewModel.cs
using System;

namespace Parking.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Parking/Models/Vehicle.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Parking.Models
{
    public class Vehicle
    {
        public int Id { get; set; }
        public string Model { get; set; }
        public string Plate { get; set; }
        public DateTime Input { get; set; }
        public DateTime Output { get; set; }

        public Vehicle(int id, string model, string plate, DateTime input, DateTime output)
        {
            Id = id;
            Model = model;
            Plate = plate;
            Input = input;
            Output = output;
        }
        public Vehicle(int id, string model, string plate, DateTime input)
        {
            Id = id;
            Model = model;
            Plate = plate;
            Input = input;
        }
        public Vehicle()
        {
        }

        public double TotalValue(double tax, DateTime input, DateTime output)
        {
            TimeSpan time = output - input;
            var total = tax * time.TotalMinutes;
            return total;

        }
    }
}

Parking/Models/VehicleFormViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Parking.Models.ViewModels
{
    public class VehicleFormViewModel
    {
        public Vehicle Vehicle { get; set; }
        public double TotalTime { get; set; }
        [DisplayFormat(DataFormatString = "{0:F2}")]
        public double TotalPrice { get; set; }
        public DateTime Now { get; set; }
    }
}

Parking/Controllers/VehiclesController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Parking.Models;
using Parking.Models.ViewModels;

namespace Parking.Controllers
{
    public class VehiclesController : Controller
    {
        private readonly ParkingContext _context;

        public VehiclesController(ParkingContext context)
        {
            _context = context;
        }
       
        // GET: Vehicles
        public async Task<IActionResult> Index()
        {
            return View(await _context.Vehicle.ToListAsync());
        }

        // GET: Vehicles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicle = await _context.Vehicle.OrderBy(x => x.Output)
                .FirstOrDefaultAsync(m => m.Id == id);
            var TimeTotal = vehicle.Output - vehicle.Input;
            var totalPrice = TimeTotal.TotalMinutes * 0.16;
            var viewModel = new VehicleFormViewModel { TotalTime = TimeTotal.TotalMinutes, Vehicle = vehicle, TotalPrice = totalPrice };
            if (vehicle == null)
            {
                return NotFound();
            }
            return View(viewModel);
        }

        // GET: Vehicles/Create
        public IActionResult Create()
        {

            return View();
        }

        // POST: Vehicles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Model,Plate,Input")] Vehicle vehicle)
        {
            var agora = DateTime.Now;
            ViewData["now"] = agora.ToString("dd/MM/yyyy");
            if (ModelState.IsValid)
            {
                _context.Add(vehicle);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(vehicle);
        }

        // GET: Vehicles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicle = await _context.Vehicle.FindAsync(id);
            vehicle.Output = DateTime.Now;
            ViewData["Plate"] = vehicle.Plate;
            ViewData["Model"] = vehicle.Model;
            if (vehicle == null)
            {
                return NotFound();
            }
            return View(vehicle);
        }

        // POST: Vehicles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Model,Plate,Input,Output")] Vehicle vehicle)
        {
            if (id != vehicle.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(vehicle);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VehicleExists(vehicle.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(vehicle);
        }

        // GET: Vehicles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicle = await _context.Vehicle
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vehicle == null)
            {
                return NotFound();
            }

            return View(vehicle);
        }

        // POST: Vehicles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var vehicle = await _context.Vehicle.FindAsync(id);
            _context.Vehicle.Remove(vehicle);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
   
        private bool VehicleExists(int id)
        {
            return _context.Vehicle.Any(e => e.Id == id);
        }
    }
}

Parking/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-xl-center btn btn-block btn-dark text-light" asp-area="" asp-controller="Vehicles" asp-action="Index">Parking 2.0</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        
                  
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Parking - Paulo Rodrigues</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Parking/Views/Vehicles/Create.cshtml
@model Parking.Models.Vehicle;

@{
    ViewData["Title"] = "Checkin";
    
   
}

<h1>@ViewData["Title"]</h1>

<h4>Vehicle</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Model" class="control-label"></label>
                <input asp-for="Model" class="form-control" />
                <span asp-validation-for="Model" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Plate" class="control-label"></label>
                <input asp-for="Plate" class="form-control"/>
                <span asp-validation-for="Plate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Input" class="control-label" ></label>
                <input asp-for="Input" class="form-control">
                <span asp-validation-for="Input" class="text-danger" ></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Parking/Views/Vehicles/Delete.cshtml
@model Parking.Models.Vehicle

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Vehicle</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Model)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Model)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Plate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Plate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Input)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Input)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Output)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Output)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Parking/Views/Vehicles/Details.cshtml
@model Parking.Models.ViewModels.VehicleFormViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Vehicle</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Vehicle.Model)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Vehicle.Model)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Vehicle.Plate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Vehicle.Plate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Vehicle.Input)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Vehicle.Input)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Vehicle.Output)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Vehicle.Output)
        </dd>
        <dt class="col-sm-2">
            Total Time
        </dt>
        <dd class="col-sm-10">
            @Model.TotalTime.ToString("F2") min
        </dd>
        <dt class="col-sm-2">
            Total Price
        </dt>
        <dd class="col-sm-10">
            R$ @Model.TotalPrice.ToString("F2")
        </dd>
    </dl>
</div>
<div>

    <a asp-action="Index" class="alert-dismissible alert">Back to List</a>
    <a asp-action="Edit" class="alert-danger alert" asp-route-id="@Model.Vehicle.Id">CheckOut</a> |
</div>

Parking/Views/Vehicles/Edit.cshtml
@model Parking.Models.Vehicle

@{
    ViewData["Title"] = "CheckOut";
}

<h1>@ViewData["Title"]</h1>

<h4>Model: @ViewData["Model"] Plate: @ViewData["Plate"]  </h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />

            <div class="form-group">
               
                <input type="hidden" asp-for="Model"  class="form-control" />
                <span asp-validation-for="Model" class="text-danger"></span>
            </div>

            <div class="form-group">
               
                <input type="hidden" asp-for="Plate" class="form-control" />
                <span asp-validation-for="Plate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label type="hidden" asp-for="Input"  class="control-label"></label>
                <input  asp-for="Input" readonly class="form-control" />
                <span asp-validation-for="Input" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Output" class="control-label"></label>
                <input asp-for="Output" class="form-control" />
                <span asp-validation-for="Output" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Checkout now" class="btn btn-danger" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Parking/Views/Vehicles/Index.cshtml
@model IEnumerable<Parking.Models.Vehicle>

@{
    ViewData["Title"] = "Vehicles Registration";
}

<h1>@ViewData["Title"] </h1>
<hr />
<p>
    <a asp-action="Create" class="alert-success alert">Check-in</a>
</p>
<br>
<table class="table table-bordered table-hover table-light">
    <thead>
        <tr>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.Model)
            </th>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.Plate)
            </th>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.Input)
            </th>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.Output)
            </th>

            <th class="text-center">Functions</th>



        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Model)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Plate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Input)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Output)
                </td>
                <td>
                    <a asp-action="Edit" class="alert-danger alert a" asp-route-id="@item.Id">Saída</a> |
                    <a asp-action="Details" class="alert-link alert " asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" class="alert-warning alert " asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>